apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-partition-order-generator
  namespace: cosmosdb-order-processor  
  labels:
    aadpodidbinding: "cosmosdb-order-processor-identity"
    app: single-partition-order-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-partition-order-generator
  template:
    metadata:
      labels:
        app: single-partition-order-generator
        aadpodidbinding: "cosmosdb-order-processor-identity"
    spec:
      containers:
      - name: mycontainer
        image: {ACR Name}.azurecr.io/cosmosdb/order-generator:latest   # update as per your environment, example myacrname.azurecr.io/cosmosdb/order-generator:latest. Do NOT add https:// in ACR Name
        imagePullPolicy: Always
        args: ["false", "true","10"]
        env:
          - name: CosmosDbConfig__Endpoint
            value: https://{Cosmos Account Name}.documents.azure.com:443/  # update as per your environment