apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-partition-order-generator
  namespace: cosmosdb-order-processor  
  labels:
    app: single-partition-order-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-partition-order-generator
  template:
    metadata:
      labels:
        app: single-partition-order-generator
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: mycontainer
        image: {ACR Name}.azurecr.io/cosmosdb/order-generator:latest   # update as per your environment, example myacrname.azurecr.io/cosmosdb/order-generator:latest. Do NOT add https:// in ACR Name
        imagePullPolicy: Always
        args: ["false", "true","25"]   # Run once and stop, generate multi partition data, Number of items to ingest per run
        env:
          - name: CosmosDbConfig__Endpoint
            value: https://{Cosmos DB Account Name}.documents.azure.com:443/  # update as per your environment