apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-order-processor
  labels:
    aadpodidbinding: "cosmosdb-order-processor-identity"
    app: cosmosdb-order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb-order-processor
  template:
    metadata:
      labels:
        app: cosmosdb-order-processor
        aadpodidbinding: "cosmosdb-order-processor-identity"
    spec:
      containers:
      - name: mycontainer
        image: {ACR Name}.azurecr.io/cosmosdb/order-processor:latest   # update as per your environment, example myacrname.azurecr.io/cosmosdb/order-processor:latest. Do NOT add https:// in ACR Name
        imagePullPolicy: Always
        env:
          - name: CosmosDbConfig__Endpoint
            value: https://{Cosmos Account Name}.documents.azure.com:443/  # update as per your environment
          - name: CosmosDbConfig__LeaseEndpoint
            value: https://{Cosmos Account Name}.documents.azure.com:443/ # update as per your environment

 
