# Deploy KEDA external scaler for Azure Cosmos DB.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosdb-scaler
  namespace: cosmosdb-order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosdb-scaler
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: cosmosdb-scaler
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - image: {ACR Name}.azurecr.io/cosmosdb/scaler:latest   # update as per your environment, example myacrname.azurecr.io/cosmosdb/scaler:latest. Do NOT add https:// in ACR Name
          imagePullPolicy: Always
          name: cosmosdb-scaler
          ports:
            - containerPort: 4050

---
# Assign hostname to the scaler application.

apiVersion: v1
kind: Service
metadata:
  name: cosmosdb-scaler
  namespace: cosmosdb-order-processor
spec:
  ports:
    - port: 4050
      targetPort: 4050
  selector:
    app: cosmosdb-scaler
