# Create namespace for the service account and services
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cosmosdb-order-processor

---
# Create service account for use with workload identity
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {Workload Identity Client ID}  # update as per your environment
  name: workload-identity-sa
  namespace: cosmosdb-order-processor
